name: covid tracker app
on: [push]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            
            - run: echo "Setting up NodeJs"
            - name: Setup NodeJs
              uses: actions/setup-node@v1
              with:
               node-version: 12.x

            - run: npm install -g surge
            - run: echo "Deploying website"
            - run: surge ./build hrcovid-19.surge.sh/ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }} 
          
            - run: echo "Please visit => ${{ secrets.SURGE_TOKEN }}"
